#!/bin/bash
seed=$(gpg --decrypt ~/.aws/aws-mfa.gpg 2>/dev/null)
if [ $? != 0 ]; then
  echo "Failed to decrypt MFA seed"
  gpg-connect-agent reloadagent /bye > /dev/null
  exit 1
fi
ps -ef | grep -v grep | grep loop_otp
if [ $? = 0 ]; then
  old_pid=$(ps -ef | grep loop_otp | grep -v grep | awk '{print $2}')
  kill -9 $old_pid
fi
export seed
loop_otp &
