#!/bin/bash
if [ "$#" != "2" ]; then
 echo "Usage: diff_json file1 file2"
 exit 1
fi
echo -n "Identical: "
jq --argfile a $1 --argfile b $2 -n 'def post_recurse(f): def r: (f | select(. != null) | r), .; r; def post_recurse: post_recurse(.[]?); ($a | (post_recurse | arrays) |= sort) as $a | ($b | (post_recurse | arrays) |= sort) as $b | $a == $b'
