#!/bin/zsh
# Usage: git_remove_all_branches
# Removes all branches except main
git checkout main
if [ $? != 0 ]; then
  echo "Error in $(pwd)"
  exit 1
fi
git pull
git branch | grep -v main | xargs git branch -D
